### PR TITLE
Start using a custom singleuser image

### PR DESCRIPTION
**Pull request by betatim**
This adds a custom image with basic "data-science" libraries (R, Julia and Python + libraries). This starts closing #4.

In addition it adds a memory limit per user pod. We guarantee each user 1GB and limit them to 4GB.

### CODE REVIEW

**Comment by betatim** [comment]
Questions to check:

* [ ] does this include `devtools` for R so people can install new packages? If yes, does it work and install stuff into the proper location?
* [ ] does `pip install` do the right thing for this repo? What about `conda`?

**Comment by gedankenstuecke** [comment]
```
ip <- as.data.frame(installed.packages()[,c(1,3:4)])
rownames(ip) <- NULL
ip <- ip[is.na(ip$Priority),1:2,drop=FALSE]
print(ip, row.names=FALSE)
```
gives you a list of all installed packages. I just played around with an R notebook and it does include `devtool` as well as `tidyverse`. I noticed that `tidyverse` is version `1.0.0`, while the current version is `1.2.1`, so an update here would be nice (though people should be able to use `devtools` to upgrade themselves but it takes forever in my try)

**Comment by betatim** [comment]
Let's see if we can get the base image modified https://github.com/jupyter/docker-stacks/pull/562

**Comment by betatim** [comment]
Let's merge this, as notebooks.oh.org is currently deployed with this setup. We can fine tune image/installed packages in a new PR.

**Pull request merged**
