### PR TITLE
beginners guide for deleting stuff

### PR DESCRIPTION
**Pull request by gedankenstuecke**

### CODE REVIEW

**Comment by betatim** [comment]
✅

**Comment by betatim** [comment]
You can also delete individual pods with `kubectl delete pod <podname>` if you need/want a slightly smaller 🔨.

**Comment by gedankenstuecke** [comment]
The tricky part though: You'll need to give the `--namespace`, which wasn't mentioned in the `docs` either, because otherwise it'll match nothing 😉

**Comment by betatim** [comment]
Ah yes! This is because you will quickly get tired of typing it and install something like https://github.com/ahmetb/kubectx

**Comment by gedankenstuecke** [comment]
That's a good thing to have learned!

**Pull request merged**
